import {createHash} from 'node:crypto'
import {existsSync, readFileSync} from 'node:fs'
import * as fs from 'node:fs/promises'
import {stripTypeScriptTypes} from 'node:module'
import * as path from 'node:path'

import {
  type BoardProblem,
  checkBoardsConfig,
  type ConfiguredBoard,
  type ConfiguredGenericBoard,
  type ConfiguredImage,
} from '@mikrojs/firmware/boards'

import {boardBuildDir, boardProjectDir, bundledBoards} from './boards.js'
import {UserError} from './errorMessage.js'
import {rewriteConfigImports} from './loadMikroConfig.js'

/** A board package's config: at its root, next to package.json. */
export const BOARDS_CONFIG = 'boards.config.ts'

/** A board that runs a generic image, with that image's chip. */
export type ResolvedGenericBoard = ConfiguredGenericBoard & {chip: string}

/**
 * The boards the package's boards.config.ts declares, and what is wrong with
 * it (see checkBoardsConfig, and a board that runs a generic image mikro
 * doesn't have); undefined when the package has none. Loaded like
 * mikro.config.ts: types stripped, the `mikro` import shimmed.
 */
export async function loadBoardsConfig(
  packageDir: string,
): Promise<
  {boards: ConfiguredBoard[]; generic: ResolvedGenericBoard[]; problems: BoardProblem[]} | undefined
> {
  const file = path.join(packageDir, BOARDS_CONFIG)
  if (!existsSync(file)) return undefined
  const source = stripTypeScriptTypes(await fs.readFile(file, 'utf8'), {mode: 'strip'})
  const code = rewriteConfigImports(source, packageDir, file, import.meta.resolve('mikro/schema'))
  let mod: {default?: unknown}
  try {
    mod = (await import(`data:text/javascript;base64,${Buffer.from(code).toString('base64')}`)) as {
      default?: unknown
    }
  } catch (e) {
    throw new UserError(`${file} failed to load`, {cause: e})
  }
  const {boards, generic, problems} = checkBoardsConfig(packageDir, mod.default)
  const bundled = bundledBoards()
  const resolved: ResolvedGenericBoard[] = []
  for (const board of generic) {
    const image = bundled.find((b) => b.name === board.firmware)
    if (image === undefined) {
      problems.push({
        specifier: board.specifier,
        message:
          `boards.config.ts, board "${board.key}": "firmware" is ${board.firmware}, which is not ` +
          `a generic board; they are ${bundled.map((b) => b.name).join(', ')}`,
      })
    } else {
      resolved.push({...board, chip: image.chip})
    }
  }
  return {boards, generic: resolved, problems}
}

/** The boards `selector` names (`--board`): an export key (`./t-display`, or
 *  `t-display`) or a board name. All of them without one. */
export function selectBoards<T extends {key: string; name: string}>(
  boards: T[],
  selector: string | undefined,
): T[] {
  if (selector === undefined) return boards
  const key = selector === '.' || selector.startsWith('./') ? selector : `./${selector}`
  const selected = boards.filter((b) => b.key === key || b.name === selector)
  if (selected.length === 0) {
    throw new UserError(
      `boards.config.ts has no board "${selector}". Its boards:\n` +
        boards.map((b) => `  ${b.key} (${b.name})`).join('\n'),
    )
  }
  return selected
}

/** `value` as a quoted CMake argument. */
function cmakeString(value: string): string {
  return `"${value.replace(/[\\"$]/g, (c) => `\\${c}`)}"`
}

/** The CMakeLists.txt of the firmware project `mikro fw build` builds a board
 *  from: the board's name, description and native modules, so the project also
 *  builds on its own (`mikro idf -C .mikro/fw-<board> -B .mikro/build-fw-<board>
 *  menuconfig`). Its settings and partition table are the sdkconfig.defaults
 *  and partitions.csv beside it, the chip is -DIDF_TARGET (boardBuildArgs). */
function projectCmake(board: ConfiguredBoard): string {
  return [
    `# Generated by mikro fw build from boards.config.ts. Don't edit.`,
    `cmake_minimum_required(VERSION 3.22)`,
    `include($ENV{IDF_PATH}/tools/cmake/project.cmake)`,
    `set(MIKROJS_BOARD_NAME ${cmakeString(board.name)})`,
    ...(board.description === undefined
      ? []
      : [`set(MIKROJS_BOARD_DESCRIPTION ${cmakeString(board.description)})`]),
    `set(MIKROJS_NATIVE_MODULES ${cmakeString(board.nativeModules.join(';'))})`,
    `find_package(MikroFirmware REQUIRED COMPONENTS esp32 NO_DEFAULT_PATH)`,
    `project(mikrojs)`,
    ``,
  ].join('\n')
}

/** Write `content` unless the file already has it (keeping its mtime, so
 *  the build stays incremental). Whether it wrote. */
async function writeIfChanged(file: string, content: string): Promise<boolean> {
  if (existsSync(file) && (await fs.readFile(file, 'utf8')) === content) return false
  await fs.writeFile(file, content)
  return true
}

/** The chip a file names: `CONFIG_IDF_TARGET="esp32c6"` in an sdkconfig,
 *  `IDF_TARGET:STRING=esp32c6` in a CMakeCache.txt. */
function targetIn(file: string, pattern: RegExp): string | undefined {
  if (!existsSync(file)) return undefined
  return pattern.exec(readFileSync(file, 'utf8'))?.[1]
}

/**
 * Write the firmware project for `board`, or for one of its images, in
 * `.mikro/fw-<board>` (`.mikro/fw-<board>+no-ble`) and return its folder. An
 * image's settings come after the board's. ESP-IDF applies sdkconfig.defaults
 * only to a new sdkconfig and builds a build folder for one chip, so a changed
 * setting, the board's or @mikrojs/firmware's own (`firmwareDefaults`), drops
 * the old sdkconfig, and a changed chip the build folder too.
 */
export async function writeBoardProject(
  packageDir: string,
  board: ConfiguredBoard,
  image?: ConfiguredImage,
  firmwareDefaults = '',
): Promise<string> {
  const dir = boardProjectDir(packageDir, board.key, image?.name)
  const buildDir = boardBuildDir(packageDir, board.key, image?.name)
  await fs.mkdir(dir, {recursive: true})
  const fragments = await Promise.all(
    board.sdkconfig.map(async (file) => `# ${file}\n${await fs.readFile(file, 'utf8')}\n`),
  )
  if (firmwareDefaults !== '') {
    const hash = createHash('sha256').update(firmwareDefaults).digest('hex').slice(0, 16)
    fragments.unshift(`# @mikrojs/firmware's defaults: ${hash}\n`)
  }
  if (image) fragments.push(`# the ${image.name} image\n${image.settings.join('\n')}\n`)
  await writeIfChanged(path.join(dir, 'CMakeLists.txt'), projectCmake(board))
  const settingsChanged = await writeIfChanged(
    path.join(dir, 'sdkconfig.defaults'),
    fragments.join(''),
  )
  const partitions = path.join(dir, 'partitions.csv')
  if (board.partitions === undefined) await fs.rm(partitions, {force: true})
  else await writeIfChanged(partitions, await fs.readFile(board.partitions, 'utf8'))

  const sdkconfig = path.join(dir, 'sdkconfig')
  const configured = targetIn(sdkconfig, /^CONFIG_IDF_TARGET="([^"]*)"/m)
  if (settingsChanged || (configured !== undefined && configured !== board.chip)) {
    await fs.rm(sdkconfig, {force: true})
  }
  const built = targetIn(path.join(buildDir, 'CMakeCache.txt'), /^IDF_TARGET:STRING=(.*)$/m)
  if (built !== undefined && built !== board.chip) {
    await fs.rm(buildDir, {recursive: true, force: true})
  }
  return dir
}

/** idf.py arguments that build `board` (or one of its images) from
 *  `projectDir` into its build folder, for the board's chip. A board's own
 *  project gets the board's name and description too, which the generated
 *  project already has. */
export function boardBuildArgs(
  packageDir: string,
  board: ConfiguredBoard,
  projectDir: string,
  image?: ConfiguredImage,
): string[] {
  return [
    '-C',
    projectDir,
    '-B',
    boardBuildDir(packageDir, board.key, image?.name),
    `-DIDF_TARGET=${board.chip}`,
    ...(board.project === undefined
      ? []
      : [
          `-DMIKROJS_BOARD_NAME=${board.name}`,
          ...(board.description === undefined
            ? []
            : [`-DMIKROJS_BOARD_DESCRIPTION=${board.description}`]),
        ]),
    'build',
  ]
}
