packages:
  - bench-site
  - dev/*
  - examples/*
  - docs
  - esp32
  - packages/@mikrojs/*
  - packages/@repo/*
  - packages/*
  - scripts

# postinstall is usually not needed because these packages ship
# native binaries via optionalDependencies
allowBuilds:
  '@serialport/bindings-cpp': false
  '@swc/core': false
  esbuild: false
  lefthook: false
  sharp: false
  workerd: false

blockExoticSubdeps: true

catalog:
  '@eslint/js': ^10.0.1
  eslint: ^10.2.1
  eslint-plugin-import: ^2.32.0
  eslint-plugin-package-json: ^1.0.0
  eslint-plugin-react-hooks: canary
  eslint-plugin-simple-import-sort: ^13.0.0
  globals: ^17.5.0
  tsx: ^4.22.0
  typescript: ^6.0.3
  typescript-eslint: ^8.59.0
  vite: ^8.0.10
  vitest: ^4.1.5

catalogs:
  node24:
    '@types/node': ^24.12.2

ignoreWorkspaceRootCheck: true

minimumReleaseAge: 1440 # minutes

trustPolicy: no-downgrade

trustPolicyExclude:
  - vite@5.4.21

trustPolicyIgnoreAfter: 1051200
