#!/usr/bin/env node
/* eslint-disable no-console */
/**
 * Build the frozen atom table from pass-1 raw bytecode blobs.
 *
 * Reads the atom section of each .bjs blob (compiled without a frozen
 * table), unions the narrow plain-string atoms in first-seen order, and
 * emits:
 *   - frozen_atoms.bin — binary table for `qjsc -A` (u32le count, then
 *     u32le len + bytes per atom)
 *   - <symbol_prefix>_frozen_atoms.h — C arrays for JS_PreloadFrozenAtoms
 *
 * Wide-char and symbol atoms are skipped: they stay dynamic, and any
 * function referencing them falls back to the copy-and-relocate load path.
 *
 * Usage: extract-atoms.js <gen_dir> <symbol_prefix> <blob1.bjs> [blob2.bjs ...]
 */
import {readFileSync, writeFileSync} from 'node:fs'
import {join} from 'node:path'

const JS_ATOM_TYPE_STRING = 1

function readLeb128(buf, pos) {
  let v = 0
  let shift = 0
  for (;;) {
    const b = buf[pos++]
    v |= (b & 0x7f) << shift
    if ((b & 0x80) === 0) break
    shift += 7
  }
  return [v >>> 0, pos]
}

const BC_VERSION = 26
const BC_VERSION_FROZEN = BC_VERSION | 0x40

/** Parse the atom section of a classic bytecode blob, returning the
 * narrow plain-string atom names as Buffers. */
function extractAtoms(blob, path) {
  // Layout: u8 version, u32 checksum, leb128 atom count, entries.
  // A misparse here degrades silently (empty table → classic blobs →
  // green build with zero memory win), so reject anything unexpected.
  if (blob[0] === BC_VERSION_FROZEN) {
    throw new Error(`${path}: pass-1 blob is already frozen-format — pipeline ordering bug`)
  }
  if (blob[0] !== BC_VERSION) {
    throw new Error(`${path}: unknown bytecode version ${blob[0]} (expected ${BC_VERSION})`)
  }
  const [count, afterCount] = readLeb128(blob, 5)
  let pos = afterCount
  const atoms = []
  for (let i = 0; i < count; i++) {
    const type = blob[pos++]
    if (type === 0) {
      pos += 4 // predefined atom id
      continue
    }
    let lenWide
    ;[lenWide, pos] = readLeb128(blob, pos)
    const isWide = lenWide & 1
    const len = lenWide >>> 1
    const size = isWide ? len * 2 : len
    if (type === JS_ATOM_TYPE_STRING && !isWide) {
      atoms.push(blob.subarray(pos, pos + len))
    }
    pos += size
  }
  return atoms
}

function cEscape(buf) {
  let out = ''
  for (const b of buf) {
    if (b >= 0x20 && b < 0x7f && b !== 0x22 && b !== 0x5c && b !== 0x3f) {
      out += String.fromCharCode(b)
    } else {
      // Octal escapes are always 3 digits here, so a following digit
      // cannot extend the escape (unlike \x).
      out += '\\' + b.toString(8).padStart(3, '0')
    }
  }
  return out
}

const [genDir, symbolPrefix, ...blobPaths] = process.argv.slice(2)
if (!genDir || !symbolPrefix || blobPaths.length === 0) {
  console.error('usage: extract-atoms.js <gen_dir> <symbol_prefix> <blob.bjs>...')
  process.exit(1)
}

const seen = new Set()
const names = []
let totalBlobBytes = 0
for (const path of blobPaths) {
  const blob = readFileSync(path)
  totalBlobBytes += blob.length
  for (const atom of extractAtoms(blob, path)) {
    const key = atom.toString('latin1')
    if (!seen.has(key)) {
      seen.add(key)
      names.push(atom)
    }
  }
}

// Real builtin bundles always introduce atoms; an empty table from
// non-trivial input means the parse silently missed the atom section.
if (names.length === 0 && totalBlobBytes > 1024) {
  console.error(
    `extract-atoms: parsed ${blobPaths.length} blobs (${totalBlobBytes} bytes) but found zero atoms — refusing to emit an empty frozen table`,
  )
  process.exit(1)
}

// Binary table for qjsc -A
const chunks = [Buffer.alloc(4)]
chunks[0].writeUInt32LE(names.length, 0)
for (const name of names) {
  const lenBuf = Buffer.alloc(4)
  lenBuf.writeUInt32LE(name.length, 0)
  chunks.push(lenBuf, name)
}
writeFileSync(join(genDir, 'frozen_atoms.bin'), Buffer.concat(chunks))

// C header for JS_PreloadFrozenAtoms
let h = '/* Auto-generated by extract-atoms.js — do not edit */\n'
if (names.length === 0) {
  h += `static const char* const ${symbolPrefix}_frozen_atom_names[] = {NULL};\n`
  h += `static const uint32_t ${symbolPrefix}_frozen_atom_lens[] = {0};\n`
} else {
  h += `static const char* const ${symbolPrefix}_frozen_atom_names[] = {\n`
  for (const name of names) {
    h += `    "${cEscape(name)}",\n`
  }
  h += '};\n'
  h += `static const uint32_t ${symbolPrefix}_frozen_atom_lens[] = {\n    `
  h += names.map((n) => n.length).join(', ')
  h += ',\n};\n'
}
h += `enum { ${symbolPrefix}_frozen_atom_count = ${names.length} };\n`
writeFileSync(join(genDir, `${symbolPrefix}_frozen_atoms.h`), h)

console.log(`extract-atoms: ${names.length} frozen atoms from ${blobPaths.length} blobs`)
