
#include <cinttypes>
#include <cstdio>

#include "mikrojs/platform.h"
#include "mikrojs/private.h"
#include "mikrojs/utils.h"

typedef struct {
    const char* name;
    const uint8_t* data;
    uint32_t data_size;
} mik_builtin_t;

/* Generated by mikrojs_generate_bytecode() in CMake — includes + lookup table.
 * Adding a new module only requires updating the MODULES list in CMakeLists.txt. */
#include "gen/mikro_builtins_table.h"
#define builtins mikro_builtins

/* External builtins registered by board/driver packages via MIK_REGISTER_BUILTIN() */
// NOLINTNEXTLINE(cppcoreguidelines-avoid-non-const-global-variables)
mik_ext_builtin_t* mik__ext_builtin_head = nullptr;

/* Deserialize bytecode into a module. Shared by core and external builtins. */
static JSModuleDef* mik__deserialize_builtin(JSContext* ctx, const char* name,
                                             const uint8_t* data, uint32_t data_size) {
    const MIKPlatform* platform = MIK_GetPlatform();

    platform->log(MIK_LOG_DEBUG, "mikrojs", "Loading builtin '%s' (%u bytes, bc_version=%u, data_ptr=%p)", name,
             data_size, data_size > 0 ? data[0] : 0, (void*)data);

    JSValue obj = JS_ReadObject(ctx, data, data_size, JS_READ_OBJ_BYTECODE);

    if (JS_IsException(obj)) {
        platform->log(MIK_LOG_ERROR, "mikrojs", "Failed to deserialize bytecode for builtin '%s' (%u bytes)", name,
                 data_size);
        /* Leave the JS exception on ctx so the caller can propagate the
         * real error (e.g. "Maximum call stack size exceeded") instead of
         * replacing it with a generic "not available" message. */
        return NULL;
    }

    if (JS_VALUE_GET_TAG(obj) != JS_TAG_MODULE) {
        platform->log(MIK_LOG_ERROR, "mikrojs", "Builtin '%s' bytecode is not a module (tag=%d)", name,
                 JS_VALUE_GET_TAG(obj));
        JS_FreeValue(ctx, obj);
        return NULL;
    }

    /* Initialize import.meta (url, env, etc.) for the builtin module */
    js_module_set_import_meta(ctx, obj, false, false);

    /* Resolve imports so the module loader is called for dependencies */
    if (JS_ResolveModule(ctx, obj) < 0) {
        platform->log(MIK_LOG_ERROR, "mikrojs", "Failed to resolve imports for builtin '%s'", name);
        JS_FreeValue(ctx, obj);
        return NULL;
    }

    JSModuleDef* m = static_cast<JSModuleDef*>(JS_VALUE_GET_PTR(obj));
    JS_FreeValue(ctx, obj);

    return m;
}

JSModuleDef* mik__load_builtin(JSContext* ctx, const char* name) {
    /* Check core builtins table */
    for (const mik_builtin_t* p = builtins; p->name != NULL; ++p) {
        if (strcmp(p->name, name) == 0) {
            return mik__deserialize_builtin(ctx, name, p->data, p->data_size);
        }
    }

    /* Check external builtins (registered by board/driver packages) */
    for (mik_ext_builtin_t* p = mik__ext_builtin_head; p != nullptr; p = p->next) {
        if (strcmp(p->name, name) == 0) {
            return mik__deserialize_builtin(ctx, name, p->data, p->data_size);
        }
    }

    return NULL;
}
