export type {
  ApplyOutcome,
  CheckinReport,
  ConfigErrorReport,
  ConfigState,
  ConfigWrite,
  Diagnostic,
  DownloadFn,
  InstallOptions,
  InstallOutcome,
  Offer,
  Ota,
  OtaBeginError,
  OtaDownloadError,
  OtaError,
  OtaInstallError,
  OtaWriteError,
  RunningBuild,
  SettleOutcome,
  StoredConfig,
  Update,
} from '@mikrojs/native/runtime/ota/types'
export {ota} from '@mikrojs/native/runtime/ota/types'
