/** Central glossary of acronyms shown as tooltips on hover. */
export const abbreviations: Record<string, string> = {
  ADC: 'Analog-to-Digital Converter',
  AP: 'Access Point',
  API: 'Application Programming Interface',
  ATT: 'Attribute Protocol',
  BLE: 'Bluetooth Low Energy',
  CBOR: 'Concise Binary Object Representation',
  CCCD: 'Client Characteristic Configuration Descriptor',
  CEST: 'Central European Summer Time',
  CLI: 'Command-Line Interface',
  CoAP: 'Constrained Application Protocol',
  CPU: 'Central Processing Unit',
  DHCP: 'Dynamic Host Configuration Protocol',
  DMA: 'Direct Memory Access',
  DNS: 'Domain Name System',
  'DNS-SD': 'DNS Service Discovery',
  EIM: 'ESP-IDF Installation Manager',
  'ESP-IDF': 'Espressif IoT Development Framework',
  ESM: 'ECMAScript Module',
  FNV: 'Fowler-Noll-Vo (hash)',
  GAP: 'Generic Access Profile',
  GATT: 'Generic Attribute Profile',
  GC: 'Garbage Collection',
  GCC: 'GNU Compiler Collection',
  GND: 'Ground (0V reference)',
  GPIO: 'General-Purpose Input/Output',
  HTTP: 'Hypertext Transfer Protocol',
  IDE: 'Integrated Development Environment',
  HTTPS: 'HTTP Secure',
  I2C: 'Inter-Integrated Circuit',
  IoT: 'Internet of Things',
  JSON: 'JavaScript Object Notation',
  JTAG: 'Joint Test Action Group',
  LAN: 'Local Area Network',
  LED: 'Light-Emitting Diode',
  LEDC: 'LED Controller (ESP peripheral)',
  MAC: 'Media Access Control',
  mDNS: 'Multicast DNS',
  MQTT: 'Message Queuing Telemetry Transport',
  MTU: 'Maximum Transmission Unit',
  NAPI: 'Node API (native addon interface)',
  NTP: 'Network Time Protocol',
  NVS: 'Non-Volatile Storage',
  OOM: 'Out Of Memory',
  POSIX: 'Portable Operating System Interface',
  PSRAM: 'Pseudo-Static RAM (external SPI memory)',
  PWM: 'Pulse-Width Modulation',
  QSPI: 'Quad Serial Peripheral Interface',
  RAM: 'Random Access Memory',
  REPL: 'Read-Eval-Print Loop',
  RFC: 'Request For Comments',
  RGB: 'Red, Green, Blue',
  RGBW: 'Red, Green, Blue, White',
  RNG: 'Random Number Generator',
  ROM: 'Read-Only Memory',
  RPC: 'Remote Procedure Call',
  RSSI: 'Received Signal Strength Indicator',
  RTC: 'Real-Time Clock',
  RTOS: 'Real-Time Operating System',
  RX: 'Receive',
  SDK: 'Software Development Kit',
  SNTP: 'Simple Network Time Protocol',
  SPI: 'Serial Peripheral Interface',
  SRAM: 'Static RAM',
  SSID: 'Service Set Identifier',
  STA: 'Station (WiFi mode)',
  TLS: 'Transport Layer Security',
  TX: 'Transmit',
  UART: 'Universal Asynchronous Receiver-Transmitter',
  UDP: 'User Datagram Protocol',
  USB: 'Universal Serial Bus',
  UTC: 'Coordinated Universal Time',
  UTF: 'Unicode Transformation Format',
  UUID: 'Universally Unique Identifier',
  WASM: 'WebAssembly',
  WHATWG: 'Web Hypertext Application Technology Working Group',
}
