/** Central glossary of acronyms shown as tooltips on hover. */
export const abbreviations: Record<string, string> = {
  ADC: 'Analog-to-Digital Converter',
  API: 'Application Programming Interface',
  BLE: 'Bluetooth Low Energy',
  CBOR: 'Concise Binary Object Representation',
  CEST: 'Central European Summer Time',
  CLI: 'Command-Line Interface',
  CPU: 'Central Processing Unit',
  DMA: 'Direct Memory Access',
  'ESP-IDF': 'Espressif IoT Development Framework',
  ESM: 'ECMAScript Module',
  GC: 'Garbage Collection',
  GND: 'Ground (0V reference)',
  GPIO: 'General-Purpose Input/Output',
  HTTP: 'Hypertext Transfer Protocol',
  IDE: 'Integrated Development Environment',
  HTTPS: 'HTTP Secure',
  I2C: 'Inter-Integrated Circuit',
  IoT: 'Internet of Things',
  JSON: 'JavaScript Object Notation',
  LED: 'Light-Emitting Diode',
  mDNS: 'Multicast DNS',
  MQTT: 'Message Queuing Telemetry Transport',
  NAPI: 'Node API (native addon interface)',
  NTP: 'Network Time Protocol',
  NVS: 'Non-Volatile Storage',
  POSIX: 'Portable Operating System Interface',
  PSRAM: 'Pseudo-Static RAM (external SPI memory)',
  PWM: 'Pulse-Width Modulation',
  QSPI: 'Quad Serial Peripheral Interface',
  RAM: 'Random Access Memory',
  REPL: 'Read-Eval-Print Loop',
  RGB: 'Red, Green, Blue',
  RTC: 'Real-Time Clock',
  RTOS: 'Real-Time Operating System',
  SDK: 'Software Development Kit',
  SNTP: 'Simple Network Time Protocol',
  SPI: 'Serial Peripheral Interface',
  SSID: 'Service Set Identifier',
  TLS: 'Transport Layer Security',
  UART: 'Universal Asynchronous Receiver-Transmitter',
  USB: 'Universal Serial Bus',
  UTC: 'Coordinated Universal Time',
  WASM: 'WebAssembly',
}
