name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: pnpm

      - run: pnpm install --frozen-lockfile
      - run: pnpm build:ts

  lib:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Init submodules
        run: git submodule update --init packages/@mikrojs/quickjs/deps/quickjs packages/@mikrojs/native/deps/nanocbor

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: pnpm

      - run: pnpm install --frozen-lockfile

      - run: cmake -B packages/@mikrojs/native/build packages/@mikrojs/native -DBUILD_TESTING=ON
      - run: cmake --build packages/@mikrojs/native/build
      - run: ctest --test-dir packages/@mikrojs/native/build --output-on-failure
