name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - uses: pnpm/setup@703c52620218391530e48b9e8870d5c0082e1b9b # v2
        with:
          runtime: node@24
          cache: true
          require-lockfile: true

      - run: pnpm build:ts

      - run: pnpm typecheck
      - run: pnpm lint
      - run: pnpm fmt:check
      - run: pnpm knip
