name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - uses: pnpm/setup@fbda4c85fc2e1e08721cd8763afea8f48d60f024 # v3
        with:
          runtime: node@24
          cache: true
          require-lockfile: true

      - run: pnpm build:ts

      - run: pnpm typecheck
      - run: pnpm lint
      - run: pnpm fmt:check
      - run: pnpm knip
